import Footer from "./components/layout/footer";
import Header from "./components/layout/header";
import Topbar from "./components/layout/topbar";
import "./globals.scss";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <div>
        <Topbar/>
        <Header/>
        {children}
        <Footer/>
        </div>
      </body>
    </html>
  );
}
